services:

  datalakes3:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    command: server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - datalakes3_vol:/data

  datavirtualisation:
    image: trinodb/trino
    ports:
      - "8080:8080"
    volumes:
      - datavirtu_catalog:/etc/trino/catalog

volumes:
  datalakes3_vol:
  datavirtu_catalog: